fedora-silverblue/silverblue-docs

modules/ROOT/pages/toolbox.adoc
This is a rewrite of the toolbox docs, but I've tried to incorporate points and material from the original.
Main goals: add more detail and refinement. Cover all the essential information that a new user might need, particularly one who isn't very familiar with the Linux command line.
=> refine toolbox.adoc

modules/ROOT/pages/toolbox.adoc
The adoc link for podman was reversed, flip it to properly link to podman.io but only display 'podman'
=> Fix podman adoc formatting

modules/ROOT/pages/getting-started.adoc
I think `toolbox` should be a clear peer of flatpak and rpm-ostree.
At some point I'd like to rework this page so we move `toolbox`
basics here, and demote `rpm-ostree` details to a separate page.
The rpm-ostree section is reworked to give clear examples of
packages to try layering and that need to be layered if desired.
And similarly give examples for `override replace`.  Let's not
emphasize `override remove` at all as its uses are obscure.
=> getting-started: Bring toolbox up as peer, rework rpm-ostree

modules/ROOT/nav.adoc, modules/ROOT/pages/troubleshooting.adoc
Guide to some of the more commonly reported problems.
Closes #2
=> Add initial troubleshooting guide

modules/ROOT/pages/troubleshooting.adoc
Workaround related to installation failures when pre existing EFI partition
is found
=> Add extra installation workaround to troubleshooting.adoc

build.sh, nginx.conf, preview.sh
Pushing again as I had messed up my fork. Sorry.
This commit also brings this repo structure (more) in lne with Fedora Docs template repo (see #42 which this PR is meant to close)
Tested on FSB30 and Ubuntu 19.04
A test on Mac would be appreciated.
Thanks!
=> Add `podman` for build and preview

modules/ROOT/nav.adoc, modules/ROOT/pages/contributing.adoc
Created a contributing page with an initial set of conventions.
There is some overlapping with https://silverblue.fedoraproject.org/contribute
but I think the Docs pages are easier to update and are the right place for the contributing section.
=> Add `contributing.adoc` and update `nav.adoc`

modules/ROOT/pages/technical-information.adoc
=> Fix typo in technical-information.adoc

modules/ROOT/pages/toolbox.adoc
The canonical address is now https://github.com/containers/toolbox.
=> Update Toolbox's GitHub project link

modules/ROOT/pages/reading-and-resources.adoc, modules/ROOT/pages/toolbox.adoc, modules/ROOT/pages/updates-upgrades-rollbacks.adoc
missing spaces creates warning in Fedora docs internationalization system, preventing us to find real generation issues
=> suppress indentation warning

modules/ROOT/pages/updates-upgrades-rollbacks.adoc
The upgrade instructions are outdated. For example, they say there is not a UI method for upgrades.
Also, minor update to cli steps.
=> Update the Upgrade instructions with latest info

modules/ROOT/pages/getting-started.adoc, modules/ROOT/pages/reading-and-resources.adoc, modules/ROOT/pages/technical-information.adoc
Both OSTree and rpm-ostree have moved their documentation hosting to GitHub from readthedocs.io. While the links referring to the home pages still work via a redirect the ones referring to a specific page end up returning a 404, so this fixes that while also skipping the redirect for the links that still work.
=> Update links to OSTree and rpm-ostree documentation

modules/ROOT/pages/faq.adoc
> This reverts commit 04006c39e19ae9174bb7aee53aabbf9d1a38747f.
Support of Adobe Flash [has ended](https://www.adobe.com/products/flashplayer/end-of-life.html). I guess it will be good to drop everything related to it from Fedora Docs? 😃
=> Remove Adobe Flash plugin related part from FAQ

modules/ROOT/pages/troubleshooting.adoc
existed -> exited, as can be seen in https://github.com/ostreedev/ostree/blob/15878c935a886a1a5d25b771c2cf68c7b1c01936/tests/test-concurrency.py#L64
=> Fix typo in troubleshooting.adoc

modules/ROOT/pages/toolbox.adoc
In my previous commit I made an oversight and one of the blocks was not
properly styled.
Also, until now the "Commands and usage" section used question/answers
format for command description. I expanded the description in the
previous commit and that caused to show the shortcomming of the format.
Only the first paragraph is considered the answer. This causes
misallignment of the text. With this the questions are turned into 3rd
level titles. This also allows to link to the command description.
=> toolbox: Adjust style

modules/ROOT/pages/getting-started.adoc
`<<toolbox.adoc,toolbox>>` refers to an anchor on the same page with ID `toolbox.adoc`.
As recommended on [their docs](https://docs.asciidoctor.org/asciidoc/latest/macros/inter-document-xref/), the best way to reference other files is `xref:<file>[<text>]`
=> Fix toolbox reference on getting started

modules/ROOT/pages/getting-started.adoc
I updated the section about rpm-ostree usage to include information about the latest features such as applying changes from pending deployment using `rpm-ostree ex apply-live' and ability to download packages using links from bodhi and koji.
=> Update section about rpm-ostree usage

.gitignore, modules/ROOT/pages/contributing.adoc
Package Maintainer Docs have moved
from wiki to docs.fedoraproject.org.
Update links to point to the new location.
=> Update wiki links

modules/ROOT/pages/updates-upgrades-rollbacks.adoc
There was a mismatch between the major versions mentioned at lines 44 and 50. Rather than just fix this, I also updated the other references to refer to the current version.
=> Make version references match

antora.yml, site.yml
This should fix the substitution on the Fedora built & hosted version of the docs.
Thanks for Rafael Fontenelle @rffontenelle for the report.
=> Move asciidoc attributes to antora.yml

modules/ROOT/pages/tips-and-tricks.adoc
This commit expands on the `istoolbx` alias by showing how it can be used to update the prompt so that no extra commands are necessary to hint to the user that they are in a toolbox and in which toolbox they currently reside.
=> Add example of toolbox state changing the prompt

modules/ROOT/pages/contributing.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/getting-started.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/installation.adoc, modules/ROOT/pages/reading-and-resources.adoc, modules/ROOT/pages/technical-information.adoc, modules/ROOT/pages/tips-and-tricks.adoc, modules/ROOT/pages/toolbox.adoc, modules/ROOT/pages/troubleshooting.adoc, modules/ROOT/pages/updates-upgrades-rollbacks.adoc
See individual commits for a readable diff.
Align the style for the entire documentation to prefer one sentence per line. This has the following advantages:
- Asciidoc properly combines lines of text into a single paragraph
- This keeps the Git diff readable and minimal while keeping line lengths reasonable
- Some Asciidoc functionnality does not interact well with hard wrapped lines
=> Collection of styling and other minor fixes

antora.yml, modules/ROOT/pages/troubleshooting.adoc, modules/ROOT/pages/updates-upgrades-rollbacks.adoc
Fix some variable usage in code blocks and add version variable.
~Currently on top of https://github.com/fedora-silverblue/silverblue-docs/pull/124 for simplicity. Will be easier to review once #124 is merged.~
=> Use a variable to set the Fedora 36 version

antora.yml, modules/ROOT/pages/contributing.adoc, modules/ROOT/pages/faq.adoc, modules/ROOT/pages/getting-started.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/installation.adoc, modules/ROOT/pages/toolbox.adoc, modules/ROOT/pages/troubleshooting.adoc, modules/ROOT/pages/updates-upgrades-rollbacks.adoc
Small fixes found during the manual sync with the Kinoite docs.
Fixes: https://github.com/fedora-silverblue/silverblue-docs/pull/134
---
updates-upgrades-rollbacks: Minor style fixes
---
*: Use Fedora Silverblue consistently as name
Make sure that we always use the full name.
=> Use Fedora Silverblue consistently & small updates-upgrades-rollbacks style fixes

modules/ROOT/pages/tips-and-tricks.adoc
I've (anecdotally) seen a number of folks complaining about using RPM Fusion with Silverblue and the challenges that come with that.
Let's just admit the obvious and give users the straight-forward way of enabling the repos.
=> tips: add instructions for using RPM Fusion

modules/ROOT/pages/tips-and-tricks.adoc
Add instructions to hide the default browser installed in the image from the menues in the interface.
This is better than using `rpm-ostree override remove` as it does not mutate the image and keeps updates fast.
=> tips&tricks: Hide the default browser in the interface

modules/ROOT/pages/faq.adoc, modules/ROOT/pages/index.adoc, modules/ROOT/pages/updates-upgrades-rollbacks.adoc
There's two broken links I found that could be easily replaced with `xref:` &mdash; `{docs-url}/something` results in a duplicate `/` ([`https://docs.fedoraproject.org/en-US/fedora-silverblue//updates-upgrades-rollbacks/#upgrading`](https://docs.fedoraproject.org/en-US/fedora-silverblue//updates-upgrades-rollbacks/#upgrading)) and breaks the relative CSS style links.
In addition, I made sure that deployment pinning link goes to the right location in the page and does not depend on the variant name.
After the change there's no remaining references to the `{docs-url}` variable. It could be removed to prevent reappearance of such links.
=> Replace absolute links with xrefs

modules/ROOT/pages/installation.adoc
Adding a small paragraph about this issue, as proposed in https://github.com/fedora-silverblue/issue-tracker/issues/3#issuecomment-1637154862
=> Add LUKS keyboard issue to the known limitations

modules/ROOT/pages/faq.adoc, modules/ROOT/pages/installation.adoc, modules/ROOT/pages/troubleshooting.adoc, modules/ROOT/pages/updates-upgrades-rollbacks.adoc
installation: Use code block for commands
---
installation: Add link to dual boot issue
---
fixup! installation: Use code block for commands
---
troubleshooting: Remove unneeded list continuation '+'
---
faq: Update versions to variables
Also set '$' for commands.
---
updates-upgrades-rollbacks: Add more rollback examples
Add an example that fetches the ostree log and deploys an arbitrary
version from the repo.
Fixes: https://github.com/fedora-silverblue/silverblue-docs/issues/155
=> installation: Use code block for commands

modules/ROOT/pages/troubleshooting.adoc
On page "Troubleshooting", section "Using NVIDIA drivers" fixed the link which is currently pointing to a incorrect link.
=> Fixed RPM fusion documentation link under - Using NVIDIA drivers

antora.yml
Noticed while syncing our docs for release.
I'd bump sericea-docs directly, but making the change here and merging it to our downstream is a better approach :smiley:
=> antora: update for Fedora 39 release

modules/ROOT/pages/getting-started.adoc
fix #169 
context: https://fedoramagazine.org/searching-for-packages-with-rpm-ostree-search/
=> fix #169 : mention rpm-ostree search function

modules/ROOT/pages/troubleshooting.adoc
Provides steps for resetting root/user password from the "Rescue Mode". Loosely based on the generic Fedora instructions found at https://docs.fedoraproject.org/en-US/quick-docs/reset-root-password/#_how_to_reset_the_root_password_in_rescue_mode
Closes https://github.com/fedora-silverblue/issue-tracker/issues/524
=> troubleshooting: reset password from rescue mode

modules/ROOT/pages/toolbox.adoc
See https://debarshiray.wordpress.com/2021/11/10/toolbox-is-now-toolbx/
Language here attempts to mirror CoreOS docs:
* "A toolbox" is unchanged
* References to the `toolbox` binary are unchanged (or clarified)
* "Toolbox container" is changed to "Toolbx container"
* The name of the project itself is changed
=> Change "Toolbox" references to "Toolbx"

modules/ROOT/pages/troubleshooting.adoc
Adds `initcall_blacklist=simpledrm_platform_driver_init` to kargs to keep up to date with https://rpmfusion.org/Howto/NVIDIA#OSTree_.28Silverblue.2FKinoite.2Fetc.29
This is needed for LUKS password screen (https://github.com/fedora-silverblue/issue-tracker/issues/477), without it booting the system gets stuck on some NVidia GPUs.
=> docs: add initcall_blacklist to kargs

modules/ROOT/pages/faq.adoc
simple change to add the new-ish search function to the docs. could've sworn this was added before/somewhere else...
=> add rpm-ostree search functionality to faq.adoc

modules/ROOT/pages/installation.adoc
This flag is recommended for filesystems smaller than 5 GiB, but currently neither `mkfs.btrfs` nor Blivet adds it automatically.
This should help with preventing things like https://github.com/fedora-silverblue/issue-tracker/issues/626.
=> Add warning about mkfs.btrfs --mixed flag

modules/ROOT/pages/tips-and-tricks.adoc, modules/ROOT/pages/updates-upgrades-rollbacks.adoc
updates-upgrades-rollbacks: Split rebase into a section
---
RPM Fusion: Add note on updates page
- Link to the RPM Fusion instructions in tips & tricks from the updates
page in the major updates section.
- split the RPM Fusion instruction in two sections to make it clear
which parts is needed for what.
=> RPM Fusion: Add note on updates page
