- modules/ROOT/pages/silverblue-guide.adoc
Replace "faltpak" with "flatpak"
> Fix a typo

- modules/ROOT/pages/upgrades.adoc
Tested myself. Credits jiri Eischmann.
> How to upgrade from F29 to F30

- modules/ROOT/pages/silverblue-guide.adoc
I added new information to the OS Upgrades section of the Silverblue Guide document.
> Added OS Upgrade information.

- modules/ROOT/pages/first-login.adoc
Update the list of flatpak sources to include the
Fedora registry.
> Mention the Fedora registry

- modules/ROOT/nav.adoc
- modules/ROOT/pages/silverblue-guide.adoc
- modules/ROOT/pages/toolbox.adoc
> Toolbox docs

- modules/ROOT/pages/toolbox.adoc
Minor polish to the toolbox docs.
> polish toolbox.adoc

- modules/ROOT/pages/silverblue-guide.adoc
Added some info on fingerprint reader setup.
> Add fingerprint reader documentation to Silverblue guide.

- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/getting-started.adoc
- modules/ROOT/pages/index.adoc
- modules/ROOT/pages/installation.adoc
- modules/ROOT/pages/technical-information.adoc
- modules/ROOT/pages/updates-upgrades-rollbacks.adoc
Polish up the docs after the user guide rewrite.
> general polish

- modules/ROOT/pages/getting-started.adoc
Fix typo flatpakts -> flatpaks
> Fix typo flatpakts -> flatpaks

- modules/ROOT/pages/getting-started.adoc
> Fix a minor punctuation error

- modules/ROOT/pages/troubleshooting.adoc
Sorry for not providing a description. I must have done something silly.
> Add  `toolbox` issue workaround with `podman` > `1.2.0`

- modules/ROOT/pages/toolbox.adoc
This PR could close https://github.com/fedora-silverblue/silverblue-docs/issues/23 perhaps?
If not enough, I am willing to create a conventions' doc but not sure if it should be targeting users that are reading the docs or possible docs' contributors.
> Add `sudo` to `dnf` command

- modules/ROOT/pages/troubleshooting.adoc
To improve troubleshooting based on feedback from https://github.com/containers/libpod/issues/3219#issuecomment-497896987
> Add oneliner for toolbox issue created by `podman` > `1.2.0`

- modules/ROOT/pages/troubleshooting.adoc
> Adds section about resetting toolbox permissions

- modules/ROOT/pages/faq.adoc
The answer text was incomplete and the link was partially correct
See also: https://discussion.fedoraproject.org/t/fedora-silverblue-on-the-marketing-infographics-campaign/1862
> Fix `faq.adoc` section relating to Eclipse

- README.md
Fixed also a typo and added nginx.conf to structure
> Add podman to README.md

- modules/ROOT/pages/troubleshooting.adoc
Also add override reset instructions.
> Fix troubleshooting.doc for podman 1.4.0

- modules/ROOT/pages/faq.adoc
Also corrected a small typo in the FAQ
> Addi to FAQ: how to compare two commits

- modules/ROOT/pages/troubleshooting.adoc
Removed a space between `usermod` options
> Fix: troubleshooting.doc

- modules/ROOT/pages/faq.adoc
Closes https://github.com/fedora-silverblue/silverblue-docs/issues/28
> Add: Adobe Flash plugin installation to FAQ

- modules/ROOT/pages/installation.adoc
Note: under "Known Limitations" the only change was to the word 'seperate' which was changed to 'separate'.  Not sure why it crossed the whole sentence.
> Minor typo and missing idea correction

- modules/ROOT/pages/faq.adoc
@jlebon FYI, incorporated your feedback and created PR. Thanks.
> Add how to upgrade while keeping current deployment

- modules/ROOT/pages/faq.adoc
> Fix typos in faq.adoc

- modules/ROOT/pages/updates-upgrades-rollbacks.adoc
provide upgrade instructions for latest release (31)
> update instructions for major upgrades

- modules/ROOT/pages/contributing.adoc
- modules/ROOT/pages/troubleshooting.adoc
- modules/ROOT/pages/updates-upgrades-rollbacks.adoc
Thanks in advance for merging.
> Fix minor typos

- modules/ROOT/pages/toolbox.adoc
The Toolbox documentation is quite bare and in few places inaccurate. It needed an update.
> Update toolbox documentation

- modules/ROOT/pages/toolbox.adoc
Thanks in advance for reviewing !
> toolbox.adoc: fix typo

- build.sh
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/getting-started.adoc
- modules/ROOT/pages/index.adoc
- modules/ROOT/pages/installation.adoc
- modules/ROOT/pages/reading-and-resources.adoc
- modules/ROOT/pages/technical-information.adoc
- modules/ROOT/pages/toolbox.adoc
- modules/ROOT/pages/updates-upgrades-rollbacks.adoc
- preview.sh
*: Minor whitespace fixes
---
preview: Use a fully qualified name for the container image
> Minor whitespace fix and use a fully qualified name for the container image used in preview

- antora.yml
- site.yml
This is compatible with both Antora 2.3.4 & 3.0.
See commit and:
- https://lists.fedoraproject.org/archives/list/docs@lists.fedoraproject.org/thread/OLVIJP7AENG3LSVHT7RMXUN7UEBOCBS3/
- https://discussion.fedoraproject.org/t/antora-v3-release-and-impact-on-fedora-docs/35788/3
- https://pagure.io/fedora-docs/docs-fp-o/pull-request/178
> Update configuration for Antora 3.0

- build.sh
- preview.sh
See https://pagure.io/fedora-docs/template
> build & preview: Update with latest version from template

- modules/ROOT/nav.adoc
- modules/ROOT/pages/tips-and-tricks.adoc
Adds a new section containing general tips and tricks for working with
rpm-ostree based operating systems.
@travier Tagging you here due to the sync to the Kinoite docs, in case this gets approval. :)
> docs: Add new "Tips and Tricks" section

- build.sh
See https://pagure.io/fedora-docs/template
> build: Update with latest version from template

- modules/ROOT/pages/contributing.adoc
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/getting-started.adoc
- modules/ROOT/pages/index.adoc
- modules/ROOT/pages/installation.adoc
- modules/ROOT/pages/reading-and-resources.adoc
- modules/ROOT/pages/technical-information.adoc
- modules/ROOT/pages/toolbox.adoc
- modules/ROOT/pages/troubleshooting.adoc
- modules/ROOT/pages/updates-upgrades-rollbacks.adoc
- site.yml
This makes the documentation more generic and mostly a copy/paste for
Kinoite. This will help share improvements in both documentations.
> Use Asciidoc attributes

- modules/ROOT/pages/contributing.adoc
- modules/ROOT/pages/faq.adoc
- modules/ROOT/pages/troubleshooting.adoc
- modules/ROOT/pages/updates-upgrades-rollbacks.adoc
Split from https://github.com/fedora-silverblue/silverblue-docs/pull/124 to simplify review.
> Minor fixes

- build.sh
- site.yml
See https://gitlab.com/fedora/docs/templates/fedora-docs-template
> Sync with Fedora Docs template changes

- modules/ROOT/pages/faq.adoc
Allow Pinning to be in it's own subsection and appear in table of contents and enable linking to it
> fix pinning section

- modules/ROOT/pages/updates-upgrades-rollbacks.adoc
> updates: Filter remotes by arch as well

- modules/ROOT/pages/troubleshooting.adoc
From https://pagure.io/fedora-kde/kinoite-docs/c/ad152540432bc8a0d31454506b9ccb0e4db1fd89?branch=main
> troubleshooting: NVIDIA: Link to RPM Fusion setup doc

- modules/ROOT/pages/getting-started.adoc
Hello, I have added a section about how to add additional repositories, since it has been brought up in the Matrix chat a couple of times.
> Add an "Adding Additional Repositories" section to the getting-started docs.

- modules/ROOT/pages/troubleshooting.adoc
troubleshooting: Update NVIDIA and split DKMS/kmods section
Update NVIDIA section to mention Universal Blue and clarify
instructions.
Add links to current issues with the NVIDIA drivers.
Split the DKMS part into another section to mention kmods & akmods.
Fixes: https://github.com/fedora-silverblue/silverblue-docs/issues/153
---
troubleshooting: Minor rewording
---
troubleshooting: Add external repo example
Fixes: https://github.com/fedora-silverblue/silverblue-docs/issues/152
> troubleshooting: Update NVIDIA, mention uBlue, minor fixes, external repo example

- modules/ROOT/pages/technical-information.adoc
Based on https://github.com/fedora-silverblue/silverblue-docs/pull/89
> technical-information: Update filesystem layout info

- modules/ROOT/pages/toolbox.adoc
Add smaller text to indicate the project is spelled correctly.
> toolbox: it's not a typo

- modules/ROOT/pages/getting-started.adoc
Also mention `Recommends=false` setting.
> Soften recommended software management methods stance

- modules/ROOT/pages/installation.adoc
- See https://github.com/fedora-silverblue/issue-tracker/issues/650
> installation: Add third-party repo warning
